name: Remove .env Files
on: [push]

jobs:
  remove-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Delete .env files
        run: |
          git config --global user.email "Robot@sipkes"
          git config --global user.name "Robot"
          if git ls-files | grep -q '^\.env$'; then
            echo "Found .env file - removing..."
            git rm --cached .env
            git commit -m "Automatically removed .env file"
            git push
          else
            echo "✅ No exact .env file found - nothing to remove"
          fi
